@startuml
actor User
participant Main
participant AppConfig
participant MeetingController
participant InputView
participant OutputView
participant MeetingService
participant MeetingRepository

== 메뉴에서 "모임 생성" 선택 ==
User -> Main : start()

Main -> AppConfig : new AppConfig()

AppConfig --> Main : new MeetingController

Main -> MeetingController : start()



== 입력 받기 ==
MeetingController -> InputView : read("모임 정보 입력")
InputView --> MeetingController : date, MeetingTime, topic, place

== 모임 생성 요청 ==
MeetingController -> MeetingService : createMeeting(date, MeetingTime, topic, place, host(Member)
activate MeetingService

MeetingService -> MeetingService : new Meeting(id, date, MeetingTime, topic, place, host)\n(도메인 생성)


== 저장 ==
MeetingService -> MeetingRepository : save(Meeting)
activate MeetingRepository
MeetingRepository --> MeetingService : 저장 완료
deactivate MeetingRepository

MeetingService --> MeetingController : Meeting
deactivate MeetingService

== 출력 ==
AppController -> OutputView : printCreateSuccess(Meeting)

@enduml